<?php

/**
 * @file
 * Enable and uninstall message broker module.
 */

/**
 * Implements hook_uninstall().
 */
function message_broker_integration_uninstall() {
  variable_del('message_broker_integration_implementation');
  variable_del('message_broker_integration_self');
}

/**
 * Implements hook_enable().
 */
function message_broker_integration_enable() {
  drupal_set_message(t('See the configuration page !url for the message broker integration to get started.',
    array(
      '!url' => l('admin/config/system/message_broker_integration',
                      'admin/config/system/message_broker_integration'))));
}
