<?php

/**
 * @file
 * Integration into main module, configuration page and enabling of autoloading.
 */

/**
 * Implements hook_message_broker_implementation().
 */
function message_broker_amqp_message_broker_implementation() {
  return array(
    'amqp' => array(
      'title' => t('AMQP'),
      'description' => t('An implementation that uses an external AMQP compliant message broker like RabbitMQ to send and consume messages.'),
      'factoryMethod' => '_message_broker_amqp_create_implementation',
    ),
  );
}

/**
 * Internal method for registering the PhpAmqpLib namespace.
 */
function _message_broker_amqp_setup_autoload() {
  static $registered = FALSE;

  if (!$registered) {
    $registered = TRUE;
    $finder = xautoload_get_finder();
    $library_path = libraries_get_path('phpamqp');

    $finder->registerNamespaceRoot('PhpAmqpLib', $library_path);
  }
}

/**
 * Collects the parameters needed to construct the implementation.
 *
 * @return array
 *   Parameters for implementing class.
 * @throws MessageBrokerException
 */
function _message_broker_amqp_collect_params() {
  $params = array();
  $params['host'] = variable_get('message_broker_amqp_host', 'localhost');
  $params['port'] = variable_get('message_broker_amqp_port', '5672');
  $params['username'] = variable_get('message_broker_amqp_username', 'guest');
  $params['password'] = variable_get('message_broker_amqp_password', 'guest');
  $params['vhost'] = variable_get('message_broker_amqp_vhost', "/");

  $config_path = variable_get('message_broker_amqp_config', '');

  if (empty($config_path)) {
    throw new MessageBrokerException('No json configuration path set!');
  }

  $config_file = file_get_contents($config_path);

  if ($config_file === FALSE) {
    throw new MessageBrokerException('The json configuration file was not read successfully!');
  }

  $config = json_decode($config_file, TRUE);

  if ($config === NULL) {
    throw new MessageBrokerException('The json configuration was not parsed successfully!');
  }

  $params['config'] = $config;

  return $params;
}

/**
 * Creates the AMQP implementation.
 *
 * @param array $consumers
 *   All consumers.
 * @param string $self_name
 *   Name of this drupal instance.
 *
 * @return \AmqpMessageBroker
 *   Created AMQP implementation.
 */
function _message_broker_amqp_create_implementation($consumers, $self_name) {
  _message_broker_amqp_setup_autoload();
  $params = _message_broker_amqp_collect_params();

  require_once 'amqp_message_broker.inc';

  return new AmqpMessageBroker($params, $consumers);
}

/**
 * Implements hook_menu().
 */
function message_broker_amqp_menu() {
  $items = array();

  $items['admin/config/system/message_broker_amqp'] = array(
    'title' => 'AMQP Message Broker Configuration',
    'description' => 'Settings for the AMQP message broker implementation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('message_broker_amqp_settings'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Settings form for the amqp configuration.
 *
 * @param array $form
 *   Form.
 * @param array $form_state
 *   Form state.
 *
 * @return array
 *   Settings form.
 */
function message_broker_amqp_settings($form, &$form_state) {
  $form['intro'] = array('#markup' => '<p>' . t('Enter host and credentials for the AMQP compliant message broker you want to use.') . '</p>');

  $form['message_broker_amqp_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Host'),
    '#default_value' => variable_get('message_broker_amqp_host', 'localhost'),
  );

  $form['message_broker_amqp_port'] = array(
    '#type' => 'textfield',
    '#title' => t('Port'),
    '#default_value' => variable_get('message_broker_amqp_port', '5672'),
  );

  $form['message_broker_amqp_vhost'] = array(
    '#type' => 'textfield',
    '#title' => t('Vhost'),
    '#default_value' => variable_get('message_broker_amqp_vhost', "/"),
  );

  $form['message_broker_amqp_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => variable_get('message_broker_amqp_username', 'guest'),
  );

  $form['message_broker_amqp_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#default_value' => variable_get('message_broker_amqp_password', 'guest'),
  );

  $form['config_intro'] = array('#markup' => '<p>' . t('Specify the path to the message broker configuration file which contains the definitions for all exchanges and queues.') . '</p>');

  $form['message_broker_amqp_config'] = array(
    '#type' => 'textfield',
    '#title' => t('Path to json configuration file'),
    '#default_value' => variable_get('message_broker_amqp_config', ''),
  );

  return system_settings_form($form);
}

/**
 * Validates the configuration form.
 *
 * @param array $form
 *   Form.
 * @param array $form_state
 *   Form state.
 */
function message_broker_amqp_settings_validate($form, &$form_state) {
  if (!empty($form_state['values']['message_broker_amqp_config'])) {
    if (!file_exists($form_state['values']['message_broker_amqp_config'])) {
      form_set_error('message_broker_amqp_config', t('The json file was not found, please check the path.'));
      return;
    }

    $config_file = file_get_contents($form_state['values']['message_broker_amqp_config']);
    $config = json_decode($config_file, TRUE);

    if ($config === NULL) {
      form_set_error('message_broker_amqp_config', t('The JSON file was not parsed successfully.'));
    }
  }
}
