<?php

/**
 * Implements hook_enable. This will set the configuration path
 * in the existing integration modules.
 */
function message_broker_integration_example_enable() {
    if (module_exists('message_broker_dummy_integration')) {
        $configPathDummy = variable_get('message_broker_dummy_integration_config');

        if (empty($configPathDummy)) {
            variable_set('message_broker_dummy_integration_config', drupal_get_path('module', 'message_broker_integration_example') . '/example_config.json');
            drupal_set_message(t('The json configuration file path for the dummy message broker integration was set. See !url for the message broker example.', array('!url' => l('admin/config/system/message_broker_integration_example', 'admin/config/system/message_broker_integration_example'))));
        }
    }
    
    if (module_exists('message_broker_amqp_integration')) {
        $configPathDummy = variable_get('message_broker_amqp_integration_config');

        if (empty($configPathDummy)) {
            variable_set('message_broker_amqp_integration_config', drupal_get_path('module', 'message_broker_integration_example') . '/example_config.json');
            drupal_set_message(t('The json configuration file path for the AMQP message broker integration was set. See !url for the message broker example.', array('!url' => l('admin/config/system/message_broker_integration_example', 'admin/config/system/message_broker_integration_example'))));
        }
    }
}

